version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=312Caju
      - POSTGRES_USER=caju_user
      - POSTGRES_DB=caju_bank